
DROP TABLE IF EXISTS ADDRESS;  
CREATE TABLE ADDRESS(
  ADRESS_ID INT AUTO_INCREMENT  PRIMARY KEY,
  STREET VARCHAR(250) NOT NULL,
  CITY VARCHAR(250) NOT NULL,
    STATE VARCHAR(250) NOT NULL,
      PIN_CODE VARCHAR(250) NOT NULL
  
);


DROP TABLE IF EXISTS PERSON;  
CREATE  TABLE PERSON(
  
  PERSON_ID INT AUTO_INCREMENT  PRIMARY KEY,
  PERSON_FIRST_NAME VARCHAR(250) NOT NULL,
  PERSON_LAST_NAME VARCHAR(250) NOT NULL,
   ADRESS_ID INT(250) NOT NULL
    /* FOREIGN KEY(adressId) REFERENCES Adress(ADRESS_ID) */
  );


 
INSERT INTO   ADDRESS(STREET ,CITY ,STATE ,PIN_CODE ) values ('VijethaStreer','Secndrabad','telangana','500032');
INSERT INTO   ADDRESS(STREET ,CITY ,STATE ,PIN_CODE ) values ('Gachibowli','Hyderabad','telangana','500055');
INSERT INTO   ADDRESS(STREET ,CITY ,STATE ,PIN_CODE ) values ('Balaji Street','Tirupati','Andhrapradesh','500044');


INSERT INTO   PERSON(PERSON_FIRST_NAME ,  PERSON_LAST_NAME ,  ADRESS_ID) values ('Shivani','Shiv',1);
INSERT INTO   PERSON(PERSON_FIRST_NAME ,  PERSON_LAST_NAME ,  ADRESS_ID) values ('Sai','Goud',2);
INSERT INTO   PERSON(PERSON_FIRST_NAME ,  PERSON_LAST_NAME ,  ADRESS_ID) values ('Balaji','Basnnagari',3);


